
server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.45.101.192:3306/third?characterEncoding=utf-8
    username: root
    password: 123456
redis:          #配置redis
  database: 0
  host: localhost
  port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置mybatis-plus将日志打印到控制台
  mapper-locations: classpath:mapper/**/*Mapper.xml # mapper映射文件 - classpath:mybatis/mapper/**/*.xml
  resources:
    static-locations: file:D:\thirdworkspace\img\uploads
  mvc:
    static-path-pattern: /**
#  tomcat:
#    basedir: img/tomcat


